name: Web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
     - 'Frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          cd Frontend
          npm install
          CI=''
          npm run build
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_START_LOGIN_PAGE_URL: ${{ secrets.REACT_APP_START_LOGIN_PAGE_URL }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_HEADER: ${{ secrets.REACT_APP_API_HEADER }}
          REACT_APP_API_ENDPOINT: ${{ secrets.REACT_APP_API_ENDPOINT }}
          REACT_APP_OAUTH_AUTHORITY: ${{ secrets.REACT_APP_OAUTH_AUTHORITY }}
    
      - name: Get DateTime as tag for the container
        id: get_datetime
        run: |
          current_timestamp=$(date +%s)
          formatted_datetime=$(date -u -d "@${current_timestamp}" +"%Y%m%d%H%M%S")
          echo "::set-output name=formatted_datetime::$formatted_datetime"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy web Container App 
        uses: azure/container-apps-deploy-action@v1 
        with: 
          appSourcePath: ${{ github.workspace }}/Frontend
          dockerfilePath: Dockerfile
          acrName: bcacreastus
          containerAppName: bc-ca-web-poc-ai-eastus-test
          resourceGroup: bc-rg-poc-ai-test
          imageToBuild: bcacreastus.azurecr.io/poc-ai-web:latest

      - name: Deploy the container app 
        uses: azure/cli@v2
        with: 
          cliversion: 2.30.0
          inlineScript: |
            az containerapp update \
              --name bc-ca-web-poc-ai-eastus-test \
              --resource-group bc-rg-poc-ai-test \
              --image bcacreastus.azurecr.io/poc-ai-web:latest \
              --cpu 1.0 \
              --memory 2.0Gi \
              --min-replicas 1 \
              --max-replicas 1 \
              --revision-suffix ${{ steps.get_datetime.outputs.formatted_datetime }}          
